### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by nightkr** [HeisenBugDev/Crafter#1]
There is already a gem named [Crafter](http://rubygems.org/gems/crafter).

**Comment by hunterboerner** [comment]
There are many gems with the same name. The solution is generally to just call it something like `minecraft-crafter`.

@k2b6s9j is a rename necessary?

**Comment by nightkr** [comment]
Well, regardless, currently the README is just plain wrong.

**Comment by hunterboerner** [comment]
Fixed 0e908bfaf5b9f78b8180ba9f1e8843f53a5135f2
